window.ECO_DATA = {
  categories: [
    { name: "Pinturas", icon: "🎨", description: "Paisajes, memoria visual y color sobre lienzo." },
    { name: "Esculturas", icon: "🗿", description: "Piezas en madera, barro, piedra y materiales mixtos." },
    { name: "Textiles", icon: "🧵", description: "Bordados, telares y piezas tejidas con identidad." },
    { name: "Artesanías", icon: "🏺", description: "Objetos artísticos hechos a mano con técnicas tradicionales." },
    { name: "Fotografía", icon: "📷", description: "Miradas documentales, culturales y contemporáneas." }
  ],
  artists: [
    {
      id: "art-01",
      name: "Teodoro Cano",
      origin: "Papantla, Veracruz",
      technique: "Escultura y muralismo",
      avatar: "artista-01.svg",
      bio: "Artista inspirado por la memoria comunitaria, la madera, los símbolos antiguos y el color de las fiestas populares."
    },
    {
      id: "art-02",
      name: "Ana Xochitl",
      origin: "Oaxaca, Oaxaca",
      technique: "Textil y pigmentos naturales",
      avatar: "artista-02.svg",
      bio: "Creadora textil que trabaja con bordado, tintes orgánicos y relatos familiares transmitidos entre generaciones."
    },
    {
      id: "art-03",
      name: "María Tének",
      origin: "Tantoyuca, Veracruz",
      technique: "Bordado y arte popular",
      avatar: "artista-03.svg",
      bio: "Su obra combina motivos florales, geometría indígena y escenas cotidianas de la Huasteca."
    },
    {
      id: "art-04",
      name: "Julián Montes",
      origin: "Puebla, Puebla",
      technique: "Pintura acrílica",
      avatar: "artista-04.svg",
      bio: "Pintor de paisajes emocionales, mercados, montes y arquitectura popular."
    }
  ],
  artworks: [
    {
      id: "obra-01",
      title: "Valle de la memoria",
      artistId: "art-04",
      artistName: "Julián Montes",
      category: "Pinturas",
      price: 8500,
      technique: "Óleo sobre lienzo",
      dimensions: "90 x 60 cm",
      year: 2025,
      origin: "Puebla, Puebla",
      certificate: true,
      stock: 1,
      featured: true,
      image: "obra-01.svg",
      tags: ["paisaje", "montaña", "memoria"],
      description: "Paisaje cálido que interpreta la relación entre territorio, nostalgia y comunidad."
    },
    {
      id: "obra-02",
      title: "Cielo de barro",
      artistId: "art-04",
      artistName: "Julián Montes",
      category: "Pinturas",
      price: 5400,
      technique: "Acrílico",
      dimensions: "70 x 50 cm",
      year: 2024,
      origin: "Puebla, Puebla",
      certificate: true,
      stock: 1,
      featured: false,
      image: "obra-02.svg",
      tags: ["cielo", "campo", "acrílico"],
      description: "Obra de color sereno que representa la calma del campo después de la lluvia."
    },
    {
      id: "obra-03",
      title: "Fiesta del río",
      artistId: "art-01",
      artistName: "Teodoro Cano",
      category: "Pinturas",
      price: 6750,
      technique: "Técnica mixta",
      dimensions: "80 x 55 cm",
      year: 2026,
      origin: "Papantla, Veracruz",
      certificate: true,
      stock: 1,
      featured: true,
      image: "obra-03.svg",
      tags: ["fiesta", "río", "color"],
      description: "Composición vibrante inspirada en celebraciones comunitarias cercanas al río."
    },
    {
      id: "obra-04",
      title: "Niebla del pueblo",
      artistId: "art-04",
      artistName: "Julián Montes",
      category: "Pinturas",
      price: 4100,
      technique: "Acuarela",
      dimensions: "50 x 35 cm",
      year: 2023,
      origin: "Xalapa, Veracruz",
      certificate: false,
      stock: 1,
      featured: false,
      image: "obra-04.svg",
      tags: ["acuarela", "niebla", "pueblo"],
      description: "Acuarela suave sobre caminos, casas y montañas cubiertas por neblina."
    },
    {
      id: "obra-05",
      title: "Raíz ceremonial",
      artistId: "art-01",
      artistName: "Teodoro Cano",
      category: "Esculturas",
      price: 12200,
      technique: "Madera tallada",
      dimensions: "48 x 30 x 24 cm",
      year: 2025,
      origin: "Papantla, Veracruz",
      certificate: true,
      stock: 1,
      featured: true,
      image: "obra-05.svg",
      tags: ["madera", "ceremonia", "totonaca"],
      description: "Escultura en madera con formas simbólicas que evocan tradición, espiritualidad y conexión con la naturaleza."
    },
    {
      id: "obra-06",
      title: "Guardián del monte",
      artistId: "art-01",
      artistName: "Teodoro Cano",
      category: "Esculturas",
      price: 9800,
      technique: "Barro cocido",
      dimensions: "42 x 28 x 22 cm",
      year: 2024,
      origin: "Papantla, Veracruz",
      certificate: true,
      stock: 1,
      featured: false,
      image: "obra-06.svg",
      tags: ["barro", "monte", "guardián"],
      description: "Figura protectora inspirada en relatos rurales y espíritus del monte."
    },
    {
      id: "obra-07",
      title: "Canto antiguo",
      artistId: "art-01",
      artistName: "Teodoro Cano",
      category: "Esculturas",
      price: 14600,
      technique: "Piedra y pigmento",
      dimensions: "52 x 35 x 28 cm",
      year: 2026,
      origin: "Papantla, Veracruz",
      certificate: true,
      stock: 1,
      featured: true,
      image: "obra-07.svg",
      tags: ["piedra", "ritual", "antiguo"],
      description: "Pieza sólida con pigmentos minerales y una presencia ceremonial."
    },
    {
      id: "obra-08",
      title: "Máscara del sol",
      artistId: "art-01",
      artistName: "Teodoro Cano",
      category: "Artesanías",
      price: 7300,
      technique: "Madera policromada",
      dimensions: "36 x 28 cm",
      year: 2023,
      origin: "Papantla, Veracruz",
      certificate: true,
      stock: 1,
      featured: false,
      image: "obra-08.svg",
      tags: ["máscara", "sol", "madera"],
      description: "Máscara decorativa con líneas solares, ideal para colección o espacio cultural."
    },
    {
      id: "obra-09",
      title: "Mercado al alba",
      artistId: "art-04",
      artistName: "Julián Montes",
      category: "Pinturas",
      price: 11200,
      technique: "Óleo sobre madera",
      dimensions: "100 x 70 cm",
      year: 2026,
      origin: "Puebla, Puebla",
      certificate: true,
      stock: 1,
      featured: false,
      image: "obra-09.svg",
      tags: ["mercado", "alba", "vida cotidiana"],
      description: "Escena matutina de vendedores, frutas y arquitectura popular."
    },
    {
      id: "obra-10",
      title: "Hilos del maíz",
      artistId: "art-03",
      artistName: "María Tének",
      category: "Textiles",
      price: 3900,
      technique: "Bordado artesanal",
      dimensions: "60 x 45 cm",
      year: 2025,
      origin: "Tantoyuca, Veracruz",
      certificate: true,
      stock: 2,
      featured: true,
      image: "obra-10.svg",
      tags: ["bordado", "maíz", "huasteca"],
      description: "Bordado que celebra el maíz como símbolo de alimento, origen y comunidad."
    },
    {
      id: "obra-11",
      title: "Camino de flores",
      artistId: "art-02",
      artistName: "Ana Xochitl",
      category: "Textiles",
      price: 4850,
      technique: "Telar de cintura",
      dimensions: "120 x 38 cm",
      year: 2024,
      origin: "Oaxaca, Oaxaca",
      certificate: true,
      stock: 1,
      featured: false,
      image: "obra-11.svg",
      tags: ["telar", "flores", "natural"],
      description: "Textil de telar de cintura con motivos florales y tintes naturales."
    },
    {
      id: "obra-12",
      title: "Azul de mercado",
      artistId: "art-02",
      artistName: "Ana Xochitl",
      category: "Fotografía",
      price: 2950,
      technique: "Fotografía fine art",
      dimensions: "40 x 60 cm",
      year: 2025,
      origin: "Oaxaca, Oaxaca",
      certificate: false,
      stock: 3,
      featured: false,
      image: "obra-12.svg",
      tags: ["fotografía", "mercado", "azul"],
      description: "Fotografía intervenida sobre escenas de mercado, textiles y tonos azules."
    }
  ]
};
